version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands: 
      - pwd; ls -lha


  pre_build:
    commands:
      - cp package.json layers
      - cp package-lock.json layers
      - cd layers
      - npm install --omit=dev
      - cd ..
      
  build:
    commands:
      - npm i -g esbuild 

      - sam build --debug

      # - sam package --s3-bucket aws-us-east-1-777957353822-tricklercache-pipe --force-upload --debug      
      - sam package --s3-bucket aws-us-east-1-777957353822-tricklercache-pipe --output-template-file packaged.yaml --debug
     
      - aws cloudformation package --template-file packaged.yaml --s3-bucket $S3_BUCKET --output-template-file template-export.yml --debug
     
  post_build:
    commands:
      - pwd 
      - ls  -lha

artifacts:
  files:
    - .aws-sam/**/*
    - package-lock.json
    - package.json
    - template-export.yml

