version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands: 
      - pwd; ls -lha


  pre_build:
    commands:
       
      # - mkdir nodejs
      # - npm i -omit=dev
      # - ls -lha
      # - cp -r layers/node_modules nodejs
      # - zip -r nodejs.zip nodejs
      # - rm -r nodejs
      
  build:
    commands:
     
      - sam build --debug

      - sam package --s3-bucket aws-us-east-1-777957353822-tricklercache-pipe --force-upload --debug
     
      - aws cloudformation package --template-file template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml --debug
     
  post_build:
    commands:
      - pwd 
      - ls  -lha

artifacts:
  files:
    - .aws-sam/**/*
    - package-lock.json
    - package.json
    # - node_modules/**/*
    - template-export.yml
    # - nodejs/**/*
    # - nodejs.zip
