version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
  pre_build:
    commands:
       
      - mkdir nodejs
      - npm i -omit=dev
      - ls -lha
      - cp -r node_modules nodejs
      - zip -r nodejs.zip nodejs
      - rmdir nodejs
      
  build:
    commands:
     
      - sam build --debug

      - sam package --s3-bucket aws-us-east-1-777957353822-tricklercache-pipe --debug
     
      - aws cloudformation package --template-file template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml --stack-name tricklercache --debug
     
  post_build:
    commands:
      - pwd 
      - ls  -lha

artifacts:
  files:
    - .aws-sam/**/*
    - package-lock.json
    - package.json
    - node_modules/**/*
    - template-export.yml
    # - nodejs/**/*
    # - nodejs.zip
