version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      #- rm -rf .aws-sam
      #- npm remove .aws-sam
      - pwd; 
      - ls -lha --block-size=K; 
      - SAM_CLI_TELEMETRY=0

  pre_build:
    commands:
      - npm remove .aws-sam
      #- npm run version
      #- npm cache clean --force
      #- npm remove node_modules
      #- npm remove layers
      #- mkdir layers
      #- cp package.json layers
      #- cp package-lock.json layers
      #- cd layers
      #- npm install --omit=dev
      #- npm prune --omit-dev
      #- cd ../

  build:
    commands:
      - npm install --omit=dev
      - npm prune --omit-dev
      #- npm install -g serverless
      - npm i -g esbuild #--bundle --minify --keep-names --sourcemap --debug #--target=node20.x  --platform: nodejs20.x

      #sam build deploy or package
      #- sam build --cached --parallel --debug
      #- sam build --cached --parallel --debug --use-container
      #- sam build --cached --parallel --debug --use-container --template-file packaged.yaml  
      #- sam build --parallel --debug 
      #- sam --clean --debug
      #- sam build --debug
      #- sam build --cached --parallel
      #- sam build --cached --parallel --manifest package.json
      - sam build --parallel --debug 
      # - sam package --s3-bucket aws-us-east-1-777957353822-tricklercache-pipe --force-upload --debug
      - sam package --s3-bucket aws-us-east-1-777957353822-tricklercache-pipe --output-template-file packaged.yaml --debug
      
      # Almost - only failed on permissions
      #- sam package --s3-bucket aws-eu-central-1-993487360810-s3dropbucket-pipe --output-template-file packaged.yaml --debug

      - aws cloudformation package --template-file packaged.yaml --s3-bucket $S3_BUCKET --output-template-file template-export.yml --debug

  post_build:
    commands:
      - pwd
      - ls  -lha
      - ls .aws-sam/deps -lha --block-size=K
      - ls node_modules -lha --block-size=K
      #- ls layers -lha --block-size=K
      #- ls packaged.yaml -lha --block-size=K
      #- ls template-export.yml -lha --block-size=K
      #- ls package.json -lha --block-size=K
      #- ls package-lock.json -lha --block-size=K

artifacts:
  files:
    - .aws-sam/**/*
    - package-lock.json
    - package.json
    - template-export.yml
