version: 0.2
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - ls -l
      - pwd
      - npm remove node_modules --loglevel verbose
      - npm install --loglevel verbose

  pre_build:
    commands:
      - rm -r .aws-sam

      # Discover and run unit tests in the '__tests__' directory
      #- npm run test
      
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm prune --production --loglevel verbose

      # - codebuild-breakpoint
      
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  files:
    - template-export.yml
