version: 0.2
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)

      - npm remove node_modules
      - pwd
      - ls -lh
      
      - npm install 

  pre_build:
    commands:
      - if [ -z ".aws-sam/" ]; then rm -r .aws-sam
      - pwd 
      - ls -lh

      # Discover and run unit tests in the '__tests__' directory
      #- npm run test

      
  build:
    commands: 

      - node_modules/.bin/esbuild ./src/handlers/s3-json-logger.ts --bundle --minify --sourcemap --platform=node --target=es2020 --outfile=./src/handlers/s3-json-logger.js
      - pwd 
      - ls -lh
      
      # - cd src/handlers && zip -r s3-json-logger.zip s3-json-logger.js*
      # - cd ../../
      - npm pack 

      - rm -r node_modules

      # - npm ci --loglevel verbose

      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      # - npm prune --production --loglevel verbose
      # - npm prune --omit=dev --loglevel verbose

      - npm install --omit=dev --loglevel verbose
      # - codebuild-breakpoint

      # - pwd
      # - ls -lh

      # Use AWS SAM to package the application by using AWS CloudFormation
      # - aws cloudformation package --debug --template-file template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
      - aws cloudformation package --template-file template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
      # - sam package --template-file template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
      
      - pwd 
      - ls -lh
    post_build:
      commands:
        - cd nodes_modules
        - pwd 
        - ls -lh 
        - cd ../ 

artifacts:
  files:
    - template-export.yml
