version: 0.2
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - ls -l
      - pwd
      - npm remove node_modules --loglevel verbose
      - npm install --omit-dev


  pre_build:
    commands:
      - pwd 
      - ls -l 
      # - rm -r .aws-sam


      # Discover and run unit tests in the '__tests__' directory
      #- npm run test

      
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm prune --omit-dev --loglevel verbose

      - npm install esbuild --loglevel verbose
      # - codebuild-breakpoint
      
  build:
    commands: 
      - pwd 
      - ls -l
      - ./node_modules/.bin/esbuild ./src/handlers/s3-json-logger.ts --bundle --minify --sourcemap --platform=node --target=es2020 --outfile=./src/handlers/s3-json-logger.js
      - ls -l 
      - cd src/handlers && zip -r s3-json-logger.zip s3-json-logger.js*
        # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template ./template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  files:
    - template-export.yml
