AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda-S3 Logging Project
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    PermissionsBoundary: arn:aws:iam::777957353822:policy/tricklercache-us-east-1-PermissionsBoundary
# Parameters:
#   AppId:
#     Type: String
Resources:
  dependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: nodejs18.x
      SamResourceId: dependencyLayer
    Properties:
      LayerName: dependencyLayer
      Description: Layer to Hold all Dependencies (reduce package size)
      ContentUri: s3://aws-us-east-1-777957353822-tricklercache-pipe/3c0fd418514675966096fdbbd27167fd
      CompatibleRuntimes:
      - nodejs18.x
  s3JsonLoggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function triggered on a file sent to an S3 bucket.
      Role: arn:aws:iam::777957353822:role/tricklercacheExecutionRole
      CodeUri: s3://aws-us-east-1-777957353822-tricklercache-pipe/8c9dbf85b43c564e8ae403c9efdff0ed
      Handler: s3-json-logger.s3JsonLoggerHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 624
      Timeout: 899
      Policies:
      - S3ReadPolicy:
          BucketName:
            Fn::Sub: ${BucketName}
      Layers:
      - Ref: dependencyLayer
    Metadata:
      Architecture: x86_64
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - src/handlers/s3-json-logger.ts
        External:
        - '@aws-sdk/client-s3'
        - node-fetch
        - nodejs
        - '@aws-sdk/fetch-http-handlerdeps/node-fetch'
        - '@aws-sdk/client3/package.json'
        Format: esm
        Minify: false
        OutExtension:
        - .js=.mjs
        Packages: external
        Platform: node
        Sourcemap: false
        Target: node18.12
      SamResourceId: s3JsonLoggerFunction
