# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "tricklercache"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
#resolve_s3 = true
s3 = "arn:aws:s3:::aws-us-east-1-777957353822-tricklercache-pipe"
s3_prefix = "tricklercache"
region = "us-east-1"
profile = "Acoustic-cis-dev-ecs-devteam-user"
parameter_overrides = "AppId=\"tricklercache\" "
image_repositories = []
disable_rollback = false
confirm_changeset = false
#role = "tricklercache-s3JsonLoggerFunctionRole-1HQYY60B3HZMT"
#role = "arn:aws:iam::777957353822:role/tricklercacheExecutionRole"
#role = "tricklercache-s3JsonLoggerFunctionRole-1HQYY60B3HZMT"


[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

