# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]

[default.global.parameters]
stack_name = "S3DropBucket"
resolve_s3 = false
loglevel="debug"

[default.build.parameters]
save_params = true
region = "us-east-1"
manifest = "/Users/kwlandry/Dropbox/Documents/A. Campaign/CodeFolder/A. S3DropBucket_main/s3dropbucket/package.json"
clean = true
cached = true
parallel = false
# sourcemap = true
inlinesourcemap = true
#cache_dir=".aws-sam/cache"
debug = true
template_file = "/Users/kwlandry/Dropbox/Documents/A. Campaign/CodeFolder/A. S3DropBucket_main/s3dropbucket/template.yml"
#build_dir = "/tmp/aws-toolkit-vscode/vsctk38db9d3f/output"


[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
profile = "Acoustic-cis-dev-ecs-devteam-user"
codeuri = "src/handlers/"
# basedir = './'
# parameter_overrides = "AppId=\"s3DropBucket\""
image_repositories = []
disable_rollback = false
confirm_changeset = false
#role = "tricklercache-s3JsonLoggerFunctionRole-1HQYY60B3HZMT"
#role = "arn:aws:iam::777957353822:role/tricklercacheExecutionRole"
#role = "tricklercache-s3JsonLoggerFunctionRole-1HQYY60B3HZMT"
resolve_s3 = false
#s3-bucket = "arn:aws:s3:::aws-us-east-1-777957353822-s3dropbucket-pipe"
s3_prefix = "s3dropbucket"


[default.package.parameters]
resolve_s3 = false
# s3-bucket = "arn:aws:s3:::aws-us-east-1-777957353822-s3dropbucket-pipe"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

