AWSTemplateFormatVersion: 2010-09-09
Description: Lambda-S3 Logging Project
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary
Parameters:
  AppId:
    Type: String
  # DeploymentTimestamp:
  #   Type: Number
  #   Description: Deployment preparation timestamp in milliseconds Since Epoch (injected by Stackery at deployment time)
Resources:
  s3JsonLoggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Role: arn:aws:iam::777957353822:role/tricklercacheExecutionRole
      Handler: ./src/handlers/s3-json-logger.s3JsonLoggerHandler
      Runtime: nodejs18.x
      Description: A Lambda function that logs a json file sent to S3 bucket.
      MemorySize: 128
      Timeout: 899
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub aws-${AWS::Region}-${AWS::AccountId}-${AppId}-tricklercache
      Events:
        tricklercacheEvent:
          Type: S3
          Properties:
            Bucket: !Ref tricklercache
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .json
      Layers:
        - dependencyLayer
  tricklercache:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub aws-${AWS::Region}-${AWS::AccountId}-${AppId}-tricklercache
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  s3JsonLoggerFunctionDeployTrigger:
    Type: Custom::FunctionDeployTrigger
    Properties:
      ServiceToken: !GetAtt s3JsonLoggerFunction.Arn
      DeploymentTimestamp: !Ref DeploymentTimestamp