AWSTemplateFormatVersion: 2010-09-09
Description: Lambda-S3 Logging Project
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary
Parameters:
  AppId:
    Type: String
Resources:
  s3JsonLoggerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: true
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: false
        EntryPoints: 
          - ./src/handlers/s3-json-logger.ts
        # External:
        #   - "'stream', 'crypto', 'os', 'path', 'fs', 'http', 'https', 'nise'"
        External: 
            - ./node_modules/*
    Properties:
      CodeUri: ./
      Role: arn:aws:iam::777957353822:role/tricklercacheExecutionRole
      Handler: ./src/handlers/s3-json-logger.s3JsonLoggerHandler
      Runtime: nodejs18.x
      Description: A Lambda function that logs a json file sent to S3 bucket.
      MemorySize: 512
      Timeout: 899
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${BucketName} 
      # Events:
      #   tricklercacheEvent:
      #     Type: S3
      #     Properties:
      #       Bucket: !Sub ${BucketName} 
      #       Events: s3:ObjectCreated:*
      #       Filter:
      #         S3Key:
      #           Rules:
      #             - Name: suffix
      #               Value: .json
      Layers:
        - arn:aws:lambda:us-east-1:777957353822:layer:dependencyLayer:1
  tricklercache:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tricklercache
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

