AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda-S3DropBucket Project
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    PermissionsBoundary: arn:aws:iam::777957353822:policy/S3DropBucket-eu-central-1-PermissionsBoundary
Resources:
  dependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: nodejs18.x
    Properties:
      LayerName: dependencyLayer
      Description: Layer to Hold all Dependencies (reduce package size)
      ContentUri: layers/
      CompatibleRuntimes:
        - nodejs18.x
  S3DropBucketFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function triggered on a file dropped on the S3DropBucket. The file is then processsed into Import/Update work files and Queued up to be processed as fast as Campaign APIs allow.
      Environment:
        Variables:
          NODE_OPTIONS: '--trace-warnings --unhandled-rejections=warn'
      Role: arn:aws:iam::777957353822:role/S3DropBucketExecutionRole
      CodeUri: ./
      Handler: S3DropBucket.S3DropBucketHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 508
      Timeout: 330
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${BucketName}
      Layers:
        - !Ref dependencyLayer
    Metadata:
      BuildMethod: esbuild
      Architecture: x86_64
      BuildProperties:
        Target: node18.12
        Format: esm
        Platform: node
        Packages: external
        Minify: false
        OutExtension:
          - .js=.mjs
        Sourcemap: inline
        EntryPoints:
          - src/handlers/S3DropBucket.ts
        External:
          - '@aws-sdk/client-s3'
          - node-fetch
          - nodejs
          - '@aws-sdk/fetch-http-handlerdeps/node-fetch'
          - '@aws-sdk/client3/package.json'
  S3DropBucketWorkQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function triggered by SQS Queue Events signalling new work on the Work S3 Bucket.
      Environment:
        Variables:
          NODE_OPTIONS: '--trace-warnings --unhandled-rejections=warn'
      Role: arn:aws:iam::777957353822:role/S3DropBucketExecutionRole
      CodeUri: ./
      Handler: s3DropBucketWorkQueue.S3DropBucketWorkQueueHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 330
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${BucketName}
      Layers:
        - !Ref dependencyLayer
    Metadata:
      BuildMethod: esbuild
      Architecture: x86_64
      BuildProperties:
        Target: node18.12
        Format: esm
        Platform: node
        Packages: external
        Minify: false
        OutExtension:
          - .js=.mjs
        Sourcemap: inline
        EntryPoints:
          - src/handlers/S3DropBucketWorkQueue.ts
        External:
          - '@aws-sdk/client-s3'
          - node-fetch
          - nodejs
          - '@aws-sdk/fetch-http-handlerdeps/node-fetch'
          - '@aws-sdk/client3/package.json'
  S3DropBucketSFTPFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function triggered on Schedule to look for files in a directory and SFTP them into the S3DropBucket.
      Environment:
        Variables:
          NODE_OPTIONS: '--trace-warnings --unhandled-rejections=warn'
      Role: arn:aws:iam::777957353822:role/S3DropBucketExecutionRole
      CodeUri: ./
      Handler: S3DropBucket.S3DropBucketSFTPHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 330
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${BucketName}
      Layers:
        - !Ref dependencyLayer
    Metadata:
      BuildMethod: esbuild
      Architecture: x86_64
      BuildProperties:
        Target: node18.12
        Format: esm
        Platform: node
        Packages: external
        Minify: false
        OutExtension:
          - .js=.mjs
        Sourcemap: inline
        EntryPoints:
          - src/handlers/S3DropBucketSFTP.ts
        External:
          - '@aws-sdk/client-s3'
          - node-fetch
          - nodejs
          - '@aws-sdk/fetch-http-handlerdeps/node-fetch'
          - '@aws-sdk/client3/package.json'
  S3DropBucketMaintenenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda to maintain and manage SQS Queues, S3Buckets and other assets of the S3DropBucket solution
      Environment:
        Variables:
          NODE_OPTIONS: '--trace-warnings --unhandled-rejections=warn'
      Role: arn:aws:iam::777957353822:role/S3DropBucketExecutionRole
      CodeUri: ./
      Handler: s3DropBucketMaintenance.S3DropBucketMaintenanceHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 330
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${BucketName}
      Layers:
        - !Ref dependencyLayer
    Metadata:
      BuildMethod: esbuild
      Architecture: x86_64
      BuildProperties:
        Target: node18.12
        Format: esm
        Platform: node
        Packages: external
        Minify: false
        OutExtension:
          - .js=.mjs
        Sourcemap: inline
        EntryPoints:
          - src/handlers/S3DropBucketMaintenance.ts
        External:
          - '@aws-sdk/client-s3'
          - node-fetch
          - nodejs
          - '@aws-sdk/fetch-http-handlerdeps/node-fetch'
          - '@aws-sdk/client3/package.json'
