AWSTemplateFormatVersion: 2010-09-09
Description: Lambda-S3 Logging Project
Transform: AWS::Serverless-2016-10-31
Globals: 
  Function:
    PermissionsBoundary: arn:aws:iam::777957353822:policy/tricklercache-us-east-1-PermissionsBoundary
    # !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary
# Parameters:
#   AppId:
#     Type: String
Resources:
  dependencyLayer:
    # Type: AWS::Lambda::LayerVersion
    Type: AWS::Serverless::LayerVersion 
    Metadata:
    #     BuildMethod: makefile
      BuildMethod: nodejs18.x
    Properties:
        # arn: arn:aws:lambda:us-east-1:777957353822:layer:dependencyLayer
        # RetentionPolicy: Retain
        LayerName: dependencyLayer
        Description:  Layer to Hold all Dependencies (reduce package size) 
        ContentUri: layers
        #   # S3Bucket: s3JsonLoggerDependenciesLayer
        #   # S3Key: nodejs.zip
        CompatibleRuntimes:
          - nodejs18.x

  s3JsonLoggerFunction:
    # Type: "AWS::Lambda::Function"
    Type: AWS::Serverless::Function
    Properties:
      # Environment:sam pack
      #       Variables:
      #         TEST_VAR1: testvar
      #         STAGE: prod
      #         Last Modified:  08/24/2023
      Description: A Lambda function triggered on a file sent to an S3 bucket.
      Role: arn:aws:iam::777957353822:role/tricklercacheExecutionRole 
      CodeUri: ./
      # CodeUri: src/handlers/          #---Gets reBuilt in SAM Package 
      Handler: s3-json-logger.s3JsonLoggerHandler
      Runtime: nodejs18.x
      Architectures: 
        - x86_64
      MemorySize: 752
      Timeout: 899
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${BucketName} 
      Layers:
        - !Ref dependencyLayer
    # #Build Parameters
    Metadata:    
      BuildMethod: esbuild
      Architecture: x86_64
      BuildProperties:
        # Target: es2020
        Target: node18.12
        Format: esm
        Platform: node
        Packages: external
        # mainFields: 
        #   --main-fields=module, main
        Minify: false
        OutExtension:
          - .js=.mjs
        Sourcemap: false
        EntryPoints: 
          - src/handlers/s3-json-logger.ts
        External: 
            - '@aws-sdk/client-s3'
            - 'node-fetch'
            - 'nodejs'
            - '@aws-sdk/fetch-http-handlerdeps/node-fetch'
            - '@aws-sdk/client3/package.json'
  
  
  
  #Can only define a new S3 Bucket on creation (first run), and then an existing bucket can only have a trigger added manually, 
  # tricklercache:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: tricklercache
  #     BucketEncryption:
  #       ServerSideEncryptionConfiguration:
  #         - ServerSideEncryptionByDefault:
  #             SSEAlgorithm: AES256

  #Can only define a trigger on creation, existing buckets can only have a trigger added manually, 
  # Events:                 
  #   tricklercacheEvent:
  #     Type: S3
  #     Properties:
  #       # Bucket: !Sub ${BucketName}
  #       Bucket: tricklercache 
  #       Events: s3:ObjectCreated:*
  #       Filter:
  #         S3Key:
  #           Rules:
  #             - Name: suffix
  #               Value: .json



