AWSTemplateFormatVersion: 2010-09-09
Description: Lambda-S3 Logging Project
Transform: AWS::Serverless-2016-10-31
Globals: 
  Function:
    PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary
Parameters:
  AppId:
    Type: String
Resources:
  s3JsonLoggerDependenciesLayer:
    # Type: AWS::Lambda::LayerVersion
    Type: AWS::Serverless::LayerVersion 
    Metadata:
        BuildMethod: makefile
    Properties:
        # arn: arn:aws:lambda:us-east-1:777957353822:layer:dependencyLayer
        LayerName: s3JsonLoggerDependencyLayer
        Description: s3JsonLoggerDependencyLayer
        ContentUri: nodejs.zip
        # Content:
        #   # S3Bucket: s3JsonLoggerDependenciesLayer
        #   # S3Key: nodejs.zip
        CompatibleRuntimes:
          - nodejs18.x
        RetentionPolicy: Retain

  s3JsonLoggerFunction:
    # Type: "AWS::Lambda::Function"
    Type: AWS::Serverless::Function
    Properties:
      Environment:
            Variables:
              TEST_VAR1: testvar
              STAGE: prod
              Last Modified:  08/24/2023
      Description: A Lambda function triggered on a file sent to an S3 bucket.
      # CodeUri: arn:aws:s3:::aws-us-east-1-777957353822-tricklercache-pipe      
      # CodeUri: ${codeuri}
      CodeUri: ../tricklerCache/
      Role: arn:aws:iam::777957353822:role/tricklercacheExecutionRole
      Handler: s3-json-logger.s3JsonLoggerHandler
      Runtime: nodejs18.x
      Architectures: 
        - x86_64
      MemorySize: 512
      Timeout: 899
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${BucketName} 
      Layers:
        - !Ref s3JsonLoggerDependenciesLayer
    #Build Parameters
    Metadata:    
      BuildMethod: esbuild
      Architecture: x86_64
      BuildProperties:
        Target: es2020
        Format: esm
        # mainFields: 
        #   --main-fields=module, main
        Minify: true
        OutExtension:
          - .js=.mjs
        Sourcemap: false
        EntryPoints: 
          - s3-json-logger.ts
        External: 
            - '@aws-sdk/client-s3'
        #     - 'node_modules'
            - 'node-fetch'
            - 'nodejs'
            - '@aws-sdk/fetch-http-handlerdeps/node-fetch'
  
  
  
  #Can only define a new S3 Bucket on creation (first run), and then an existing bucket can only have a trigger added manually, 
  # tricklercache:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: tricklercache
  #     BucketEncryption:
  #       ServerSideEncryptionConfiguration:
  #         - ServerSideEncryptionByDefault:
  #             SSEAlgorithm: AES256

  #Can only define a trigger on creation, existing buckets can only have a trigger added manually, 
  # Events:                 
  #   tricklercacheEvent:
  #     Type: S3
  #     Properties:
  #       # Bucket: !Sub ${BucketName}
  #       Bucket: tricklercache 
  #       Events: s3:ObjectCreated:*
  #       Filter:
  #         S3Key:
  #           Rules:
  #             - Name: suffix
  #               Value: .json



