AWSTemplateFormatVersion: 2010-09-09
Description: Lambda-S3 Logging Project
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary
Parameters:
  AppId:
    Type: String
Resources:
  s3JsonLoggerFunction:
    # Type: "AWS::Lambda::Function"
    Type: AWS::Serverless::Function      
    Metadata:    
      # CodeUri: arn:aws:s3:::aws-us-east-1-777957353822-tricklercache-pipe      
      CodeUri: deploy
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: true
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          # - ./src/handlers/s3-json-logger.ts
          - ./src/handlers/s3-json-logger.ts
        External: 
            - ./node_modules/aws-sdk/clients/s3.js
            - aws-sdk
    Properties:
      # Code:
      #     S3Bucket: arn:aws:s3:::aws-us-east-1-777957353822-tricklercache-pipe
      #     S3Bucket: !Ref "LambdaS3Bucket"
      #     # S3Key: !Ref "LambdaS3Key"
      PackageType: "Zip"
      Role: arn:aws:iam::777957353822:role/tricklercacheExecutionRole
      Handler: ./src/handlers/s3-json-logger.s3JsonLoggerHandler
      Runtime: nodejs18.x
      Description: A Lambda function that logs a json file sent to S3 bucket.
      MemorySize: 512
      Timeout: 899
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${BucketName} 
      # Events:
      #Needed on first definition, once S3 Bucket has the Trigger definition to trigger the Lambda function on 'All Create' Events then not needed anymore
      #   tricklercacheEvent:
      #     Type: S3
      #     Properties:
      #       Bucket: !Sub ${BucketName} 
      #       Events: s3:ObjectCreated:*
      #       Filter:
      #         S3Key:
      #           Rules:
      #             - Name: suffix
      #               Value: .json
      Layers:
        - arn:aws:lambda:us-east-1:777957353822:layer:dependencyLayer:1

  tricklercache:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tricklercache
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

