AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda-S3 project
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    PermissionsBoundary:
      Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary
Parameters:
  AppId:
    Type: String
Resources:
  s3JsonLoggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3JsonLoggerFunction
      Handler: src/handlers/s3-json-logger.s3JsonLoggerHandler
      Runtime: nodejs18.x
      Description: A Lambda function that logs a json file sent to S3 bucket.
      MemorySize: 128
      Timeout: 6000
      Policies:
      - S3ReadPolicy:
          BucketName:
            Fn::Sub: aws-${AWS::Region}-${AWS::AccountId}-${AppId}-simpleappbucket
      Events:
        simpleappbucketEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: simpleappbucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .json
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.s3JsonLoggerFunction0bb40ffeDepLayer
    Metadata:
      SamResourceId: s3JsonLoggerFunction
  simpleappbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: aws-${AWS::Region}-${AWS::AccountId}-${AppId}-simpleappbucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: /Users/kwlandry/Dropbox/Documents/A. Campaign/CodeFolder/A.TricklerCache_codecommit/.aws-sam/auto-dependency-layer/adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
